Update patch set 3
Patch Set 3:

This causes build failures if MSM_BSP isn't set (I'm trying to build on mako):

target thumb C: libminui <= bootable/recovery-cm/minui/graphics_overlay.c
bootable/recovery-cm/minui/graphics_overlay.c: In function 'overlay_init':
bootable/recovery-cm/minui/graphics_overlay.c:589:21: error: 'mem_info' undeclared (first use in this function)
bootable/recovery-cm/minui/graphics_overlay.c:589:21: note: each undeclared identifier is reported only once for each function it appears in

Patch-set: 3
Reviewer: Danny Baumann <1063@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0